File Handling New
p2o-lab/pimad-core pull request #9
Opened 2021-05-05 21:46 UTC by tuansondinh

pimad-core version 0.0.1-alpha7
It's capable of filehandling and deleting PEAs.

2021-05-06 10:03 UTC, tuansondinh commented
- private files have been removed from git history
- changed to previous test files
- ready for merge

2021-05-12 13:31 UTC, julorenz requested changes

2021-06-02 07:01 UTC, cheidelbach commented on src/PEAPool/PEAPool.ts
> +                //TODO: Check if splice was successful?
Fix/Solve TODO

2021-06-02 16:58 UTC, tuansondinh commented on src/Converter/Importer/Importer.ts
> +        switch (instructions.source.split('.').pop()) {
yes, pop() returns the last array element

2021-06-02 17:09 UTC, tuansondinh commented
@cheidelbach thank you for your help 👍  ,
@julorenz can you merge, please?

2021-06-02 19:42 UTC, julorenz commented on src/PEAPool/PEAPool.ts
> -                //TODO: Check if splice was successful?
Why is that check not necessary?

I would expect this.peas.find() to return undefined now.

2021-06-02 20:37 UTC, tuansondinh commented on src/PEAPool/PEAPool.ts
> -                //TODO: Check if splice was successful?
I have added a check :) but I'm not sure when that case could appear

2021-06-03 19:44 UTC, julorenz approved these changes

2021-06-03 19:44 UTC, merged